# Generated by Django 5.1.2 on 2024-12-06 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('id_team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_role', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth_user.role')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.user')),
            ],
            options={
                'db_table': 'role_user',
            },
        ),
    ]
