# Generated by Django 5.1.6 on 2025-03-17 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teamproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamproject',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
