# Generated by Django 5.1.6 on 2025-03-17 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teamproject_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamproject',
            name='tournament',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_projects', to='main.tournament'),
            preserve_default=False,
        ),
    ]
