# Generated by Django 5.1.6 on 2025-03-28 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teamproject_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название критерия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('max_score', models.PositiveIntegerField(verbose_name='Максимальный балл')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
                'db_table': 'criterion',
            },
        ),
        migrations.CreateModel(
            name='TeamAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Оценка')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='main.criterion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='main.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='main.tournament')),
            ],
            options={
                'verbose_name': 'Оценка команды',
                'verbose_name_plural': 'Оценки команд',
                'db_table': 'team_assessment',
            },
        ),
        migrations.CreateModel(
            name='TournamentCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='main.criterion')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='main.tournament')),
            ],
            options={
                'verbose_name': 'Критерий соревнования',
                'verbose_name_plural': 'Критерии соревнований',
                'db_table': 'tournament_criterion',
            },
        ),
        migrations.DeleteModel(
            name='TournamentAssessment',
        ),
    ]
