# Generated by Django 5.1.6 on 2025-04-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_criterion_teamassessment_tournamentcriterion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
